spring:
  application:
    name: reservation
    version: 1.0.2
  datasource:
    url: ${app.datasource.db-name.host}
    username: ${app.datasource.db-name.username}
    password: ${app.datasource.db-name.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 8
      minimumIdle: 4
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    org.flywaydb: WARN
    org.apache: WARN

