CREATE TABLE users (
	id INT IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
);

CREATE TABLE tables (
	id INT IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	capacity INT NOT NULL,
	status VARCHAR(20) CHECK (status in ('AVAILABLE', 'RESERVED', 'INACTIVE')) NOT NULL
);

CREATE TABLE reservations (
	id INT IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	table_id INT NOT NULL,
	date_reservation INT NOT NULL,
	status VARCHAR(20) CHECK (status in ('ACTIVE', 'CANCELED'))
);